web/authentication/urls.py
from django.urls import path
from authentication import views


app_name = 'authentication'
urlpatterns = [
    path('', views.home, name='home'),
    path('logout/', views.auth_logout, name='logout'),
    path('profile/', views.view_profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('current_user/', views.current_user, name='current_user'),
    path('change_password/', views.change_password, name='change_password'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include
import authentication
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('library/', include('library.urls')),
    path('', authentication.views.start_page)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/authentication/models.py
from django.db import models

# Create your models here.

web/authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        label="",
        widget=forms.TextInput(
            attrs={'placeholder': 'Username'}
        ))

    password = forms.CharField(
        max_length=50,
        required=True,
        label="",
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Password'}
        ))

    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "First Name"}
        ))

    last_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Last Name"}
        ))

    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Username"}
        ))

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"placeholder": "Email"}
        ))

    password1 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(
            attrs={'id': 'password', "placeholder": "Password"}
        ))

    password2 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(
            attrs={'id': 'password', "placeholder": "Repeat Password"}
        ))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "First Name"}
        ))

    last_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Last Name"}
        ))

    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Username"}
        ))

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"placeholder": "Email"}
        ))
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

web/authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseForbidden, JsonResponse, HttpResponse
from authentication.forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash

BUTTON_LOGIN = 'login'
BUTTON_REGISTER = 'register'


def start_page(request):
    # if request.user.is_authenticated:
    #     return redirect('/library')
    return render(request, 'home.html')


def current_user(request):
    cur_user = request.user
    return JsonResponse({'username': cur_user.username})


def home(request):
    if request.method == 'POST':
        if BUTTON_LOGIN in request.POST:
            return auth_login(request)
        elif BUTTON_REGISTER in request.POST:
            return register(request)
    login_form = LoginForm()
    register_form = RegisterForm()
    return render(request, 'authentication/index.html',
                  {'login_form': login_form, 'register_form': register_form, 'type': 'login'})


def auth_login(request):
    form = LoginForm(request, request.POST)
    login_form = LoginForm()
    if form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember_me = request.POST.get('remember_me')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            if not remember_me:
                request.session.set_expiry(0)
                request.session.modified = True
            return redirect('/library')
    return render(request, 'authentication/index.html',
                  {'login_form': login_form, 'register_form': form, 'type': 'login'})


def register(request):
    form = RegisterForm(request.POST)
    login_form = LoginForm()
    register_form = RegisterForm()
    if form.is_valid():
        form.save()
        return render(request, 'authentication/index.html',
                      {'login_form': login_form, 'register_form': register_form, 'type': 'login'})
    return render(request, 'authentication/index.html',
                  {'login_form': login_form, 'register_form': form, 'type': 'register'})


def auth_logout(request):
    logout(request)
    return redirect('/')


@login_required
def edit_profile(request):
    if request.method == "POST":
        user_form = EditUserForm(request.POST, instance=request.user)

        if user_form.is_valid():
            user_form.save()
            return render(request, 'authentication/profile.html', {'user': request.user})

    elif request.method == "GET":
        user_form = EditUserForm(instance=request.user)

    return render(request, 'authentication/edit_profile.html', {'user_form': user_form})


@login_required
def view_profile(request):
    return render(request, 'authentication/profile.html', {'user': request.user})


@login_required
def change_password(request):
    u = request.user
    u.set_password(request.POST['password'])
    u.save()
    update_session_auth_hash(request, u)
    return redirect('/auth/profile')

web/authentication/templates/authentication/defualt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
</head>
<body>
{% include "authentication/nav.html" %}
<div class="container py-5 d-flex flex-column justify-content-center align-items-center shadow-lg mx-auto m-5 w-25">
    {% block content %}{% endblock %}
    <div class="modal text-dark" id="myPassChangeModal">
        <div class="modal-dialog">
          <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header text-light bg-warning">
              <h4 class="modal-title">Change Password</h4>
              <button
                type="button"
                class="btn-close btn-close-white"
                data-bs-dismiss="modal"
              ></button>
            </div>
      
            <!-- Modal body -->
            <div class="modal-body">
              <form
                action="/authentication/change-password"
                method="post"
                id="password-change-form"
                class="form-container d-flex flex-column p-4 justify-content-center align-items-center"
              >
                {% csrf_token %}
      
                <div class="input-group mb-3 w-100">
                  <span class="input-group-text">New Password</span>
                  <input type="password" class="form-control" name="password" id="password" placeholder="New Password">
                </div>
      
                <input
                  type="submit"
                  value="Change"
                  class="btn btn-warning me-1"
                  style="width: 7rem"
                />
              </form>
            </div>
      
            <!-- Modal footer -->
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-danger"
                data-bs-dismiss="modal"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

web/authentication/templates/authentication/edit_profile.html
{% extends "authentication/defualt.html" %} {% load static %} {% block content%}
<img
  src="{% static 'authentication/images/4.jpg' %}"
  class="rounded-circle w-50 m-3"
  alt="profilephoto"
/>
<form method="post">
  {% csrf_token %}
  <div class="row m-2 w-100">
    <div class="col-sm"><label>Firstname: </label></div>
    <div class="col-sm">{{ user_form.first_name }}</div>
    <span style="color: #dc3545"> {{ user_form.first_name.errors }} </span>
  </div>
  <div class="row m-2 w-100">
    <div class="col-sm"><label>Lastname: </label></div>
    <div class="col-sm">{{ user_form.last_name }}</div>
    <span style="color: #dc3545"> {{ user_form.last_name.errors }} </span>
  </div>
  <div class="row m-2 w-100">
    <div class="col-sm"><label>Username: </label></div>
    <div class="col-sm">{{ user_form.username }}</div>
    <span style="color: #dc3545"> {{ user_form.username.errors }} </span>
  </div>
  <div class="row m-2 w-100">
    <div class="col-sm"><label>Email: </label></div>
    <div class="col-sm">{{ user_form.email }}</div>
    <span style="color: #dc3545"> {{ user_form.email.errors }} </span>
  </div>
  <div class="row mx-auto d-flex justify-content-center w-25">
    <a  style="padding: 0;">
      <button
        data-bs-toggle="modal"
        data-bs-target="#myPassChangeModal"
        type="button" 
        class="btn text-light mt-3"
        style="border-radius: 5px; background-color: #1c73bb; width: 200%; margin-left: -50%;"
      >
        Change Password
      </button>
    </a>
    <a style="padding: 0;">
      <button
        type="submit"
        class="btn bmt-3 text-light mt-3"
        style="border-radius: 5px; background-color: #1c73bb; width: 200%; margin-left: -50%;"
      >
        Save
      </button>
    </a>
  </div>
</form>
{% endblock %}

web/authentication/templates/authentication/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <link rel="stylesheet" href=""> -->

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="../../static/authentication/homeStyle.css" />

    <title>Home</title>
  </head>
  <body>
    <section
      id="cp"
      class="bg-light text-light text-center text-md-start bg-cover home-section section-padding position-relative"
    >
      <svg
        class="wave"
        viewBox="0 0 450 450"
        xmlns="http://www.w3.org/2000/svg"
      >
        <g>
          <title>Layer 1</title>
          <path
            stroke-width="0"
            id="svg_5"
            class="svg-path"
            d="m-40.4,407.2c195,-154 177,79 390,-4c213,-83 289,-73 402,13c113,86 208,-175 216,-163c8,12 -81,367 -81,366c0,-1 -897,-11 -896.6,-11.2c-0.4,0.2 -225.4,-46.8 -30.4,-200.8z"
            opacity="NaN"
            stroke="#000"
            fill="#00ff7f"
          />
        </g>
      </svg>
      <div class="container" style="z-index: 4; position: relative">
        <div class="row">
          <div class="col-md">
            <div class="home-text">
              <span class="text-light h1 bold-text fs-7">Uploder</span>
              <p class="text-light my-4 fw-bold">
                The best organized free drive for you!
              </p>
              <p class="text-light my-4">Just hit the button below and sign-up if you don't have an account <i>for free<i>.</p>
              <a
                href="./index.html"
                class="home-btn btn btn-warning btn-lg text-dark text-center p-3 px-5"
              >
                Login/Register
              </a>
            </div>
          </div>
          <div class="col-md"></div>
        </div>
      </div>
    </section>
    <section>
      <div id="desktop-stack">
        <div class="container stack-container">
            <div class="stack-parent" id="stack-parent-right">
                <img src="../../static/authentication/images/home/CloudUpload.png" alt="upload">
            </div>
            <div class="container">
                <h3 class="text-color fw-bold">Uploading...</h3>
                <p class="text-color" style="font-size: 1.1rem;">
                  Choose your library and organize your files like never!
                  <br>
                  Aside from 4 libraries that all users have (Movies/Music/Photos/Docs), you can create as much 
                  libraries as you want and customize them as you wish.
                  <br>
                  Don't you ever worry about another misplacement in your files.
                  <br>
                  Need to put some attachments beside your main file? You can create that as well :)  
                </p>
                <a href="#" class="link-secondary text-decoration-none">How it works? (coming soon...)</a>
            </div>
        </div>
        <br> <br>
        <div class="container stack-container">
            <div class="stack-parent" id="stack-parent-left">  
                <img src="../../static/authentication/images/home/CloudDownload.png" alt="download">
            </div>
            <div class="container">
                <h3 class="text-color fw-bold">...Downloading</h3>
                <p class="text-color" style="font-size: 1.1rem;">
                  You have already uploaded your files into your libraries?
                  <br>
                  Access them from anywhere just by logging into you account!
                  <br>
                  After Logging in you can choose your library and find the file(s) you want in them.
                  Click on whatever file you have uploaded before and click on the download button to receive 
                  them on your current device!
                  <br>
                  Ha! No need to carry a flash-memory with you everywhere :)
                </p>
                <a href="#" class="link-secondary text-decoration-none">How it works? (coming soon...)</a>
            </div>
        </div>
        <br> <br>
    </div>
    </section>
  </body>
</html>

web/authentication/templates/authentication/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"
      crossorigin="anonymous"
    /> -->
    <link rel="stylesheet" href="{% static "authentication/style.css" %}"/>
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    <title>Document</title>
</head>
<body>
<div class="container {% if type == 'register' %}right-panel-active{% endif %}" id="container">
    <div class="form-container sign-up-container">
        <form method="post" id="form-id">
            {% csrf_token %}
            <input type="hidden" name="action" value="register"/>
            <h1>Create Account</h1>
            <div class="flex-overwriter">
                {{ register_form.first_name }}
                {{ register_form.last_name }}
            </div>
            <span class="error-css">
                {{ register_form.first_name.errors }}
            </span>
            <span class="error-css">
                {{ register_form.last_name.errors }}
            </span>
            {{ register_form.username }}
            <span class="error-css">
                {{ register_form.username.errors }}
            </span>
            {{ register_form.email }}
            <span class="error-css">
                {{ register_form.email.errors }}
            </span>
            {{ register_form.password1 }}
            {{ register_form.password2 }}
            <span class="error-css">
                {{ register_form.password1.errors }}
            </span>
            <span class="error-css">
                {{ register_form.password2.errors }}
            </span>
            
{#            <div id="error-success-message">#}
{#                {% comment %} <i class="fa fa-times-circle" style="display: none;"></i> {% endcomment %}#}
{#                {% comment %} <i class="fa fa-check" style="display: none;"></i> {% endcomment %}#}
{#                {% if register_form.errors %}#}
{#                    <script>#}
{#                        console.log("here1");#}
{#                        try {#}
{#                            message = document.getElementById("error-success-message");#}
{#                            message.classList.add("error-message");#}
{#                            message.classList.remove("success-message");#}
{#                            //errLogo = document.getElementsByClassName("fa-times-circle")[0];#}
{#                            //successLogo = document.getElementsByClassName("fa-check")[0];#}
{#                            //errLogo.style.display = "inline";#}
{#                            //successLogo.style.display = "none";#}
{#                        } catch (e) {}#}
{#                    </script>#}
{#                    {% comment %} message goes here {% endcomment %}#}
{#                {% else %}#}
{#                    <script>#}
{#                        console.log("here2");#}
{#                        try {#}
{#                            message = document.getElementById("error-success-message");#}
{#                            message.classList.add("success-message");#}
{#                            message.classList.remove("error-message");#}
{#                            //errLogo = document.getElementsByClassName("fa-times-circle")[0];#}
{#                            //successLogo = document.getElementsByClassName("fa-check")[0];#}
{#                            //errLogo.style.display = "none";#}
{#                            //successLogo.style.display = "inline";#}
{#                        } catch (e) {}#}
{#                    </script>#}
{#                    {% comment %} message goes here {% endcomment %}#}
{#                {% endif %}#}
{#            </div>#}
            <button type="submit" name="register" onclick="myFunction()">Sign Up</button>
        </form>
    </div>
    <div class="form-container sign-in-container">
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="action" value="login"/>
            <h1>Sign in</h1>
            {% for field in login_form %}
                {% if field.label %}
                    <div class="flex-overwriter">
                        {{ field }}
                        <label>{{ field.label }}</label>
                    </div>
                {% else %}
                    {{ field }}
                    {{ field.errors }}
                {% endif %}
            {% endfor %}

            <button type="submit" name="login">Sign In</button>
        </form>
    </div>
    <div class="overlay-container">
        <div class="overlay">
            <div class="overlay-panel overlay-left">
                <h1 class="shadow-overlay">Want to Sign In?</h1>
                <p>Login to your personal account by clicking the link below</p>
                <button class="ghost" id="signIn">Sign In</button>
            </div>
            <div class="overlay-panel overlay-right">
                <h1>No Account?</h1>
                <p>
                    Please click on the button below and become a part of our family
                </p>
                <button class="ghost" id="signUp">Sign Up</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static "authentication/script.js" %}"></script>
</body>
</html>

web/authentication/templates/authentication/nav.html
<div>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous"
  />
  <nav class="navbar navbar-expand-sm" style="background-color: #b3d6f4">
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item ms-2">
          <a
            class="nav-link btn text-light"
            style="background-color: #1c73bb; width: 5rem"
            href="/"
            >Home</a
          >
        </li>
        <li class="nav-item ms-2">
          <a
            class="nav-link btn text-light"
            style="background-color: #1c73bb; width: 5rem"
            href="/library"
            >Libraries</a
          >
        </li>
        <li class="nav-item ms-2">
          <a
            class="nav-link btn text-dark"
            style="background-color: #fde59d; width: 5rem"
            href="{% url 'authentication:logout' %}"
            >Logout</a
          >
        </li>
      </ul>
      <a class="navbar-brand" href="{% url 'authentication:profile' %}">
        <img
          src="../../static/authentication/images/4.jpg"
          alt="Profile"
          width="50"
          height="50"
          style="border-radius: 50%"
          {%comment%}
          style="
            filter: invert(36%) sepia(99%) saturate(565%) hue-rotate(170deg)
              brightness(89%) contrast(97%);
          "
          {%endcomment%}
        />
      </a>
    </div>
  </nav>
</div>

web/authentication/templates/authentication/profile.html
{% extends "authentication/defualt.html" %}
{% load static %}
{% block content %}
    <img src="{% static 'authentication/images/4.jpg' %}" class="rounded-circle w-50 m-3" alt="profilephoto">
    <div class="row m-2 w-100">
        <div class="col-sm"><label>firstname: </label></div>
        <div class="col-sm"><input class="radix-1" type="text" readonly value="{{ user.first_name }}"></div>
    </div>
    <div class="row m-2 w-100">
        <div class="col-sm"><label>lastname: </label></div>
        <div class="col-sm"><input type="text" readonly value="{{ user.last_name }}"></div>
    </div>
    <div class="row m-2 w-100">
        <div class="col-sm"><label>username: </label></div>
        <div class="col-sm"><input type="text" readonly value="{{ user.username }}"></div>
    </div>
    <div class="row m-2 w-100">
        <div class="col-sm"><label>email: </label></div>
        <div class="col-sm"><input type="text" readonly value="{{ user.email }}"></div>
    </div>
    <div class="row w-25">
        <a href="{% url 'authentication:edit_profile' %}" class="w-25">
            <button type="submit" class="btn bmt-3 text-light mt-3"
                    style="border-radius: 5px;background-color: #1c73bb;">Edit
            </button>
        </a>
    </div>
{% endblock %}